### ISSUE TITLE
Possible evolution problem

### ISSUE THREAD

**Issue by PoUpA** [BoBeR182/PoGoBoWo#40]
Sorry haven't dived a lot in the code to fix this but it looks like the pokemon list isn't updated after evolving so the evolved pokemon is not rated well for the releasing.

**Comment by etrevis** [comment]
I checked, the pokemons list isn't updated before releasing pokemons. So actually the bot rate also the pokemon just evolded as it was before!
Anyway, I [just fixed](https://github.com/etrevis/PoGo-Bot/commit/e3ce4cab966f7bd1a106a808b059c63aebfb698d) this removing the evolved pokemon from the list. So that pokemon will be correctly rate next cycle.

**Comment by PoUpA** [comment]
thanks for the fix and update
